# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("greet.proto", :syntax => :proto3) do
    add_message "greet.HelloRequest" do
      optional :name, :string, 1
      optional :language, :string, 2
      optional :friendliness, :int32, 3
    end
    add_message "greet.HelloReply" do
      optional :greeting, :string, 1
    end
  end
end

module Greet
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("greet.HelloReply").msgclass
end
